### ISSUE TITLE
Issue in resize partition

### ISSUE THREAD

**Issue by ShashaankHari** [gregewing/windows_on_linux#1]
Hello I am trying to get windows in a docker following the medium blog and your github/docker
Docker version 27.1.1, build 6312585 on Ubuntu 24.04

when I tried resizing for both 40 and 50 with the following command

```
docker run --privileged -it --cgroupns host --name windows10 --device=/dev/kvm --device=/dev/net/tun -v /sys/fs/cgroup:/sys/fs/cgroup:rw -p 0.0.0.0:3389:3389/tcp  -e MEMORY=4096 -e CPU=4 -e DISK_SIZE=40 --cap-add=NET_ADMIN --cap-add=SYS_ADMIN gregewing/windows_on_linux:peru_windows-10-enterprise-x64-eval bash
```

```
default: Running: inline PowerShell script
    default: Resize-Partition : Size Not Supported
    default: 
    default: Extended information:
    default: The partition is already the requested size.
    default: 
    default: Activity ID: {5e2bc677-7d4f-4c02-84a7-ef6fb8df0c6a}
    default: At C:\tmp\vagrant-shell.ps1:2 char:9
    default: +         Resize-Partition -DriveLetter "C" -Size (Get-PartitionSupport ...
    default: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    default:     + CategoryInfo          : NotSpecified: (StorageWMI:ROOT/Microsoft/.../MSFT_Partition) [Resize-Partition], CimExce
    default:    ption
    default:     + FullyQualifiedErrorId : StorageWMI 4097,Resize-Partition
    default: 
    default: 
    default: 
    default: LongPathsEnabled : 1
    default: PSPath           : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem
    default: PSParentPath     : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control
    default: PSChildName      : FileSystem
    default: PSDrive          : HKLM
    default: PSProvider       : Microsoft.PowerShell.Core\Registry
    default: 
    default: 
    default: 
```

**Comment by gregewing** [comment]
The logs look normal, assuming the requested size is the same as the current size. Does the image start, but your requested disk does not get set to the right size?

**Comment by ShashaankHari** [comment]
> The logs look normal, assuming the requested size is the same as the current size. Does the image start, but your requested disk does not get set to the right size?

I have updated the post please check again, i tried both 50 and 40 gb but neither ran. And no, the image didnt run

**Comment by ShashaankHari** [comment]
Also the error occurs even when i remove the specific environment. minus the -e  DISK_SIZE=40

**Comment by gregewing** [comment]
Ok, please send me the complete log from the run (docker logs <imagename> )and the entire docker command you are using and I'll see if I can replicate the issue here, by way of trying to find a fix.

**Comment by gregewing** [comment]
I've built and pusked a new 'minimalist' and 'win10ent' image in hopes that some of teh downstream dependent software that gets bundled with the images maybe has an update in it.

let me know how you get on, and if you still need help, let me have those logs and the command you are using to start the container.

**Comment by gregewing** [comment]
Also, I noticed, when trying to recreate your config, that the minimum size of the disk for the Win10ent image is 50GB.  

I'm concerned though that the image does not start at all for you.  I'd like to help.  Please can you send me the complete output from your docker command, it may tell me something useful.  

I ran exactly the command you pasted in your initial post and it worked for me, I get the same messages, but the image does start up, and I am able to connect to it using a RDP client.

Greg.

**Comment by ShashaankHari** [comment]
> Also, I noticed, when trying to recreate your config, that the minimum size of the disk for the Win10ent image is 50GB.
> 
> I'm concerned though that the image does not start at all for you. I'd like to help. Please can you send me the complete output from your docker command, it may tell me something useful.
> 
> I ran exactly the command you pasted in your initial post and it worked for me, I get the same messages, but the image does start up, and I am able to connect to it using a RDP client.
> 
> Greg.

Yes the machine seems to be running but i am unable to connect to rdp, 

```
docker run --privileged -it --cgroupns host --name windows10 --device=/dev/kvm --device=/dev/net/tun -v /sys/fs/cgroup:/sys/fs/cgroup:rw -p 0.0.0.0:3389:3389/tcp  -e MEMORY=4096 -e CPU=4 -e DISK_SIZE=50 --cap-add=NET_ADMIN --cap-add=SYS_ADMIN gregewing/windows_on_linux:peru_windows-10-enterprise-x64-eval bash

```

```
Unable to find image 'gregewing/windows_on_linux:peru_windows-10-enterprise-x64-eval' locally
peru_windows-10-enterprise-x64-eval: Pulling from gregewing/windows_on_linux
8bf66812453d: Pull complete 
Digest: sha256:289c34f348419f9c7602072b0b46f151fd88532108d76c853f41e7950648830d
Status: Downloaded newer image for gregewing/windows_on_linux:peru_windows-10-enterprise-x64-eval
Host reports 25 VT-x cores available. This will probably work...
Linking Vagrant Image file with box source folder.
Bringing machine 'default' up with 'libvirt' provider...
==> default: Created volume larger than box defaults, will require manual resizing of
==> default: filesystems to utilize.
==> default: Creating image (snapshot of base box volume).
==> default: Creating domain with the following settings...
==> default:  -- Name:              vagrant_default
==> default:  -- Description:       Source: /vagrant/Vagrantfile
==> default:  -- Domain type:       kvm
==> default:  -- Cpus:              4
==> default:  -- Feature:           acpi
==> default:  -- Feature:           apic
==> default:  -- Feature:           pae
==> default:  -- Feature (HyperV):  name=relaxed, state=on
==> default:  -- Feature (HyperV):  name=synic, state=on
==> default:  -- Feature (HyperV):  name=vapic, state=on
==> default:  -- Feature (HyperV):  name=vpindex, state=on
==> default:  -- Clock offset:      utc
==> default:  -- Memory:            4096M
==> default:  -- Base box:          peru/windows-10-enterprise-x64-eval
==> default:  -- Storage pool:      default
==> default:  -- Image(vda):        /var/lib/libvirt/images/vagrant_default.img, virtio, 50G
==> default:  -- Disk driver opts:  cache='default'
==> default:  -- Graphics Type:     spice
==> default:  -- Graphics Websocket: 
==> default:  -- Graphics Port:     
==> default:  -- Graphics IP:       
==> default:  -- Graphics Password: Not defined
==> default:  -- Video Type:        qxl
==> default:  -- Video VRAM:        16384
==> default:  -- Video 3D accel:    false
==> default:  -- Sound Type:        ich6
==> default:  -- Keymap:            en-us
==> default:  -- TPM Backend:       passthrough
==> default:  -- INPUT:             type=mouse, bus=ps2
==> default:  -- CHANNEL:             type=spicevmc, mode=
==> default:  -- CHANNEL:             target_type=virtio, target_name=com.redhat.spice.0
==> default:  -- CHANNEL:             type=unix, mode=
==> default:  -- CHANNEL:             target_type=virtio, target_name=org.qemu.guest_agent.0
==> default:  -- RNG device model:  random
==> default: Creating shared folders metadata...
==> default: Updating domain definition due to configuration change
==> default: Starting domain.
==> default: Waiting for domain to get an IP address...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: WinRM address: 192.168.121.242:5985
    default: WinRM username: vagrant
    default: WinRM execution_time_limit: PT2H
    default: WinRM transport: negotiate
 ==> default: Machine booted and ready!
==> default: You are trying to forward to privileged ports (ports <= 1024). Most
==> default: operating systems restrict this to only privileged process (typically
==> default: processes running as an administrative user). This is a warning in case
==> default: the port forwarding doesn't work. If any problems occur, please try a
==> default: port higher than 1024.
==> default: Forwarding ports...
==> default: 3389 (guest) => 3389 (host) (adapter eth0)
==> default: 5986 (guest) => 5986 (host) (adapter eth0)
==> default: 5985 (guest) => 5985 (host) (adapter eth0)
==> default: 445 (guest) => 445 (host) (adapter eth0)
==> default: Requesting sudo for host port(s) <= 1024
==> default: Configuring and enabling network interfaces...
==> default: Running provisioner: shell...
    default: Running: inline PowerShell script
    default: Resize-Partition : Size Not Supported
    default: 
    default: Extended information:
    default: The partition is already the requested size.
    default: 
    default: Activity ID: {0989e698-7ebe-4a12-bc32-02cf431d4d3b}
    default: At C:\tmp\vagrant-shell.ps1:2 char:9
    default: +         Resize-Partition -DriveLetter "C" -Size (Get-PartitionSupport ...
    default: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    default:     + CategoryInfo          : NotSpecified: (StorageWMI:ROOT/Microsoft/.../MSFT_Partition) [Resize-Partition], CimExce
    default:    ption
    default:     + FullyQualifiedErrorId : StorageWMI 4097,Resize-Partition
    default: 
    default: 
    default: 
    default: LongPathsEnabled : 1
    default: PSPath           : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem
    default: PSParentPath     : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control
    default: PSChildName      : FileSystem
    default: PSDrive          : HKLM
    default: PSProvider       : Microsoft.PowerShell.Core\Registry
    default: 
    default: 
    default:
```
```
root@4ec795b571ad:/vagrant#  vagrant rdp
==> default: Detecting RDP info...
    default: Address: 192.168.121.242:3389
    default: Username: vagrant
==> default: Vagrant will now launch your RDP client with the connection parameters
==> default: above. If the connection fails, verify that the information above is
==> default: correct. Additionally, make sure the RDP server is configured and
==> default: running in the guest machine (it is disabled by default on Windows).
==> default: Also, verify that the firewall is open to allow RDP connections.
```
```
root@4ec795b571ad:/vagrant# vagrant status
Current machine states:

default                   running (libvirt)

The Libvirt domain is running. To stop this machine, you can run
`vagrant halt`. To destroy the machine, you can run `vagrant destroy`.
```
```
rdesktop 192.168.121.242:3389
Autoselecting keyboard map 'en-us' from locale
Core(error): tcp_connect(), unable to connect to 192.168.121.242
```

**Comment by gregewing** [comment]
Try connecting RDP to the IP Address of the Linux physical docker host on port 3389, instead of the ip address of the container.

**Comment by ShashaankHari** [comment]
> Try connecting RDP to the IP Address of the Linux physical docker host on port 3389, instead of the ip address of the container.

yep it worked.

**Comment by ShashaankHari** [comment]
have you tried persistence? im gonna try with the plugin vagrant-persistent-storage but it seems to work only with vbox (in their documentation)

**Comment by gregewing** [comment]
I did have a go with persistence, but I didn't go down that route as I figured I would likely always mount a share or an NTFS from within the image if I needed persistent data. 

Let me know how you get on. I'd be happy to update the image, or for you to fork it if you prefer.

**Comment by ShashaankHari** [comment]
if i stop the container entirely and reopen it, the file i created still exist. i havent done anything to the container, no changes

i dont want to flood this issue, but can i contact you in any other way?

> I did have a go with persistence, but I didn't go down that route as I figured I would likely always mount a share or an NTFS from within the image if I needed persistent data.
> 
> Let me know how you get on. I'd be happy to update the image, or for you to fork it if you prefer.

**Comment by gregewing** [comment]
Yes, but if you recreate the container, for example in Portainer, then the file you created will be gone. 

I propose we can close this issue as solved, and start a new thread for persistence.

**Comment by ShashaankHari** [comment]
> Yes, but if you recreate the container, for example in Portainer, then the file you created will be gone.
> 
> I propose we can close this issue as solved, and start a new thread for persistence.

I will create a new thread for persistence but we also have to acknowledge that partition resize wont always work. I tried manually resizing the partition and it showed me that only 8 gigs can be reduced from 50G in that case, to avoid confusion for people when seeing this error, you can also give a more brief note (the one you already have doesn't give that much clarity on why) that depending on the installed image the resize may not work.

**Comment by gregewing** [comment]
To be honest, that comes from
The downstream image, if it's the message I think you mean, and I have no control over it.

**Comment by ShashaankHari** [comment]
> To be honest, that comes from The downstream image, if it's the message I think you mean, and I have no control over it.

Thats what, just give it as a brief note so that people will move on and ignore the error

**Comment by gregewing** [comment]
There's this in the documentation on dockerhub:

[cid:76126bf5-6b50-436c-b5ca-837ea46eecf0]
________________________________
